### PR TITLE
fix(#68): refactor usage of bit mask u8 to be inclusive

### PR DESCRIPTION
**Pull request by danielnehrig**
Signed-off-by: Daniel Nehrig <daniel.nehrig@redteclab.com>
fix for #68

### CODE REVIEW

**Comment by h33p** [comment]
The same change needs to be made to the `bit_mask` function as well, and `cargo fmt` should be run to keep the formatting consistent.

**Comment by danielnehrig** [comment]
> The same change needs to be made to the `bit_mask` function as well, and `cargo fmt` should be run to keep the formatting consistent.

i'm a bit in a predicament with my health i'll come back to this as soon as i'm good again

**Comment by h33p** [comment]
No worries, hope you get well soon!

**Comment by h33p** [comment]
Looks good, thank you for your contribution!

**Pull request merged**
